on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build_android:
    runs-on: ubuntu22.04_x64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

#    - uses: actions/checkout@v4
#    - name: set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'zulu'
#        cache: gradle

    - name: Conan version
      run: conan --version
    - name: Android path
      run: echo "ANDROID_HOME=$ANDROID_HOME"
#    - name: Install Conan
#      run: pip install --upgrade conan
#    - name: Setup Conan default profile
#      run: conan profile detect

#    - name: Git
#      run: git submodule update --init --recursive

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set env
      if: github.event_name == 'release'
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print Release Version
      if: github.event_name == 'release'
      run: |
        echo "Release Version: $RELEASE_VERSION"
    - name: Build with Gradle
      run: |
        export PATH=/home/ubuntu/android-sdk/cmdline-tools/latest/bin/:$PATH
        yes | sdkmanager --licenses
        ANDROID_HOME=/home/ubuntu/android-sdk/ ./gradlew build
    - name: Checks
      run: ANDROID_HOME=/home/ubuntu/android-sdk/ ./gradlew tomlCheck ktlintCheck detektCheck checkSortDependencies projectHealth

    - name: Cache Conan
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: conan-${{ runner.os }}-${{ hashFiles('**/conanfile.*') }}

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: app/build
        key: build-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          build-${{ runner.os }}-
