on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build_android:
    runs-on: ubuntu22.04_x64
    environment: RELEASE_ENVIRONMENT
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Use secret
      run: |
        echo "KEY_ALIAS=$KEY_ALIAS KEYSTORE_PATH=$KEYSTORE_PATH"
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
        echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_ENV
        echo "KEYSTORE_PATH=${{ vars.KEYSTORE_PATH }}" >> $GITHUB_ENV
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEYSTORE_PATH: ${{ vars.KEYSTORE_PATH }}
    - name: Conan version
      run: conan --version
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set env
      if: github.event_name == 'release'
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print Release Version
      if: github.event_name == 'release'
      run: |
        echo "Release Version: $RELEASE_VERSION"
    - name: Build with Gradle
      run: |
        export PATH=/home/ubuntu/android-sdk/cmdline-tools/latest/bin/:$PATH
        export ANDROID_HOME=/home/ubuntu/android-sdk
        ./gradlew build
    - name: Checks
      run: ANDROID_HOME=/home/ubuntu/android-sdk/ ./gradlew tomlCheck ktlintCheck detektCheck checkSortDependencies projectHealth
