on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build_android:
    runs-on: ubuntu22.04_x64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: show alias
      run: echo "My variable is ${{ vars.KEY_ALIAS }}"
    - name: show pass
      run: echo "My variable is ${{ vars.KEYSTORE_PATH }}"

    - name: Conan version
      run: conan --version

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set env
      if: github.event_name == 'release'
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print Release Version
      if: github.event_name == 'release'
      run: |
        echo "Release Version: $RELEASE_VERSION"
    - name: Build with Gradle
      run: |
        export PATH=/home/ubuntu/android-sdk/cmdline-tools/latest/bin/:$PATH
        export ANDROID_HOME=/home/ubuntu/android-sdk
        ./gradlew build
    - name: Checks
      run: ANDROID_HOME=/home/ubuntu/android-sdk/ ./gradlew tomlCheck ktlintCheck detektCheck checkSortDependencies projectHealth
